version: '3.4'
services:
  be:
    container_name: pbl4be-prod
    image: pbl4bet1-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      target: production
    ports: 
      - 8080:80
    # volumes:
    #   - .:/src
  fe:
    container_name: pbl4fe-prod
    image: pbl4fet1-prod
    build: 
      context: ./PBL4.FE
      target: production
    ports:
      - 4200:80
      # - 49153:49153
    # volumes:
    #   - ./PBL4.FE/src:/src/src